### ISSUE TITLE
Problem with downloading the data

### ISSUE THREAD

**Issue by RealAntonVoronov** [g-luo/news_clippings#1]
Hello. Thank you for your great work, I would like to use this dataset in my own experiments, but unfortunately all links in `download.sh` are broken. I cannot visit this links neither from server nor from home laptop. Are they outdated? It would be really helpful if you provide fresh links. I receive following outputs for all downloads: 

`--2022-04-14 11:38:11--  http://news_clippings.berkeleyvision.org/embeddings/sbert_embeddings/
Resolving news_clippings.berkeleyvision.org (news_clippings.berkeleyvision.org)... 128.32.162.150
Connecting to news_clippings.berkeleyvision.org (news_clippings.berkeleyvision.org)|128.32.162.150|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-14 11:38:12 ERROR 404: Not Found.`

**Comment by g-luo** [comment]
Hi! Thank you for checking out our dataset. I'm currently able to access these links; it's possible that our server was down during the moment you were trying to download.

Could you try accessing the links again? If the problem persists I will look into an alternative download method.

**Comment by RealAntonVoronov** [comment]
Yes, now everything seems to work. Thanks.
